import { z } from "https://esm.sh/zod@3.23.8";
import type { ResourceDefinition } from "../core/types.ts";

const bookingEawbData: ResourceDefinition = {
  name: "booking_eawb_data",
  table: "booking_eawb_data",
  key: "id",
  selectable: [
    "id",
    "bookingId",
    "status",
    "reference",
    "specialHandlingCode",
    "dataSentAt",
    "confirmedAt",
    "lastError",
    "ediMessageId",
    "isConsolidation",
    "hasDocuments",
    "isSecuredCargo",
    "fwbSentAt",
    "fmaReceivedAt",
    "fohReceivedAt",
    "rcsReceivedAt",
    "securityStatus",
    "securityDeclaration",
    "awbNumber",
    "updatedAt"
  ],
  relations: ["booking", "booking_edi_messages"],
  defaultOrder: { column: "updatedAt", desc: true },
  createSchema: z.object({
    bookingId: z.number().int(),
    status: z.enum(["CREATED", "SENT", "CONFIRMED", "ERROR", "CANCELLED"]).default("CREATED"),
    reference: z.string().optional(),
    specialHandlingCode: z.enum(["ECC", "ECP", "EAW", "EAP"]).optional(),
    dataSentAt: z.string().optional(),
    confirmedAt: z.string().optional(),
    lastError: z.string().optional(),
    ediMessageId: z.number().int().optional(),
    isConsolidation: z.boolean().default(false),
    hasDocuments: z.boolean().default(false),
    isSecuredCargo: z.boolean().default(false),
    fwbSentAt: z.string().optional(),
    fmaReceivedAt: z.string().optional(),
    fohReceivedAt: z.string().optional(),
    rcsReceivedAt: z.string().optional(),
    securityStatus: z.enum(["PENDING", "APPROVED", "REJECTED"]).optional(),
    securityDeclaration: z.string().optional(),
    awbNumber: z.string().optional(),
  }),
  updateSchema: z.object({
    bookingId: z.number().int().optional(),
    status: z.enum(["CREATED", "SENT", "CONFIRMED", "ERROR", "CANCELLED"]).optional(),
    reference: z.string().optional(),
    specialHandlingCode: z.enum(["ECC", "ECP", "EAW", "EAP"]).optional(),
    dataSentAt: z.string().optional(),
    confirmedAt: z.string().optional(),
    lastError: z.string().optional(),
    ediMessageId: z.number().int().optional(),
    isConsolidation: z.boolean().optional(),
    hasDocuments: z.boolean().optional(),
    isSecuredCargo: z.boolean().optional(),
    fwbSentAt: z.string().optional(),
    fmaReceivedAt: z.string().optional(),
    fohReceivedAt: z.string().optional(),
    rcsReceivedAt: z.string().optional(),
    securityStatus: z.enum(["PENDING", "APPROVED", "REJECTED"]).optional(),
    securityDeclaration: z.string().optional(),
    awbNumber: z.string().optional(),
  }),
  allow: { list: true, get: true, create: true, update: true, delete: true },
  rbac: ({ roles, method }) => (roles.includes("admin") ? true : method !== "DELETE"),
};

export default bookingEawbData;
